// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SurvStation.Infra.Contexts;

#nullable disable

namespace SurvStation.Infra.Migrations
{
    [DbContext(typeof(FormsContext<Guid>))]
    partial class FormsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormDefinition<System.Guid>", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Key")
                        .HasName("pk_forms");

                    b.HasAlternateKey("Slug")
                        .HasName("ak_forms_slug");

                    b.ToTable("forms", (string)null);
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormItem<System.Guid>", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<string>("Config")
                        .HasColumnType("JSONB")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Key")
                        .HasName("pk_form_item_guid");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_form_item_guid_form_id");

                    b.ToTable("form_item_guid", (string)null);
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormSubmission<System.Guid>", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.Property<Guid>("FormVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_version_id");

                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Index"));

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Key")
                        .HasName("pk_form_submissions");

                    b.HasAlternateKey("Index")
                        .HasName("ak_form_submissions_index");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_form_submissions_form_id");

                    b.HasIndex("FormVersionId")
                        .HasDatabaseName("ix_form_submissions_form_version_id");

                    b.ToTable("form_submissions", (string)null);
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormSubmissionResponse<System.Guid>", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.Property<Guid>("FormItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_item_id");

                    b.Property<Guid>("FormVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_version_id");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_form_submission_responses");

                    b.HasAlternateKey("SubmissionId", "FormId", "FormVersionId", "FormItemId")
                        .HasName("ak_form_submission_responses_submission_id_form_id_form_versio");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_form_submission_responses_form_id");

                    b.HasIndex("FormVersionId")
                        .HasDatabaseName("ix_form_submission_responses_form_version_id");

                    b.ToTable("form_submission_responses", (string)null);
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormVersion<System.Guid>", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FormDefinitionKey")
                        .HasColumnType("uuid")
                        .HasColumnName("form_definition_guid_key");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Key")
                        .HasName("pk_form_versions");

                    b.HasIndex("FormDefinitionKey")
                        .HasDatabaseName("ix_form_versions_form_definition_guid_key");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_form_versions_form_id");

                    b.ToTable("form_versions", (string)null);
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormVersionItem<System.Guid>", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<string>("Config")
                        .HasColumnType("JSONB")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.Property<Guid>("FormVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_version_id");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("MetaTag")
                        .HasColumnType("text")
                        .HasColumnName("meta_tag");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Relevance", "SurvStation.Domain.Models.Forms.FormVersionItem<System.Guid>.Relevance#FormItemRelevance", b1 =>
                        {
                            b1.Property<bool>("Enabled");

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Conditions", "SurvStation.Domain.Models.Forms.FormVersionItem<System.Guid>.Relevance#FormItemRelevance.Conditions#FormItemRelevanceCondition", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Operator");

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "Expressions", "SurvStation.Domain.Models.Forms.FormVersionItem<System.Guid>.Relevance#FormItemRelevance.Conditions#FormItemRelevanceCondition.Expressions#FormItemRelevanceConditionExpression", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("Field");

                                            b3.Property<bool>("Negated");

                                            b3.Property<int>("Operator");
                                        });
                                });

                            b1
                                .ToJson("relevance")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Key")
                        .HasName("pk_form_version_item_guid");

                    b.HasAlternateKey("FormId", "FormVersionId")
                        .HasName("ak_form_version_item_guid_form_id_form_version_id");

                    b.HasIndex("FormVersionId")
                        .HasDatabaseName("ix_form_version_item_guid_form_version_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_form_version_item_guid_item_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_form_version_item_guid_parent_id");

                    b.ToTable("form_version_item_guid", (string)null);
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormItem<System.Guid>", b =>
                {
                    b.HasOne("SurvStation.Domain.Models.Forms.FormDefinition<System.Guid>", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_item_guid_forms_form_id");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormSubmission<System.Guid>", b =>
                {
                    b.HasOne("SurvStation.Domain.Models.Forms.FormDefinition<System.Guid>", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_submissions_forms_form_id");

                    b.HasOne("SurvStation.Domain.Models.Forms.FormVersion<System.Guid>", "FormVersion")
                        .WithMany()
                        .HasForeignKey("FormVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_submissions_form_versions_form_version_id");

                    b.Navigation("Form");

                    b.Navigation("FormVersion");
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormSubmissionResponse<System.Guid>", b =>
                {
                    b.HasOne("SurvStation.Domain.Models.Forms.FormDefinition<System.Guid>", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_submission_responses_forms_form_id");

                    b.HasOne("SurvStation.Domain.Models.Forms.FormVersion<System.Guid>", "FormVersion")
                        .WithMany()
                        .HasForeignKey("FormVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_form_submission_responses_form_versions_form_version_id");

                    b.HasOne("SurvStation.Domain.Models.Forms.FormVersionItem<System.Guid>", "FormItem")
                        .WithMany()
                        .HasForeignKey("FormVersionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_form_submission_responses_form_version_item_guid_form_versi");

                    b.HasOne("SurvStation.Domain.Models.Forms.FormSubmission<System.Guid>", "Submission")
                        .WithMany("Responses")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_form_submission_responses_form_submissions_submission_id");

                    b.Navigation("Form");

                    b.Navigation("FormItem");

                    b.Navigation("FormVersion");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormVersion<System.Guid>", b =>
                {
                    b.HasOne("SurvStation.Domain.Models.Forms.FormDefinition<System.Guid>", null)
                        .WithMany("Versions")
                        .HasForeignKey("FormDefinitionKey")
                        .HasConstraintName("fk_form_versions_forms_form_definition_guid_key");

                    b.HasOne("SurvStation.Domain.Models.Forms.FormDefinition<System.Guid>", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_versions_forms_form_id");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormVersionItem<System.Guid>", b =>
                {
                    b.HasOne("SurvStation.Domain.Models.Forms.FormDefinition<System.Guid>", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_version_item_guid_forms_form_id");

                    b.HasOne("SurvStation.Domain.Models.Forms.FormVersion<System.Guid>", "FormVersion")
                        .WithMany("Items")
                        .HasForeignKey("FormVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_form_version_item_guid_form_versions_form_version_id");

                    b.HasOne("SurvStation.Domain.Models.Forms.FormItem<System.Guid>", "FormItem")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_form_version_item_guid_form_item_guid_item_id");

                    b.HasOne("SurvStation.Domain.Models.Forms.FormVersionItem<System.Guid>", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_form_version_item_guid_form_version_item_guid_parent_id");

                    b.Navigation("Form");

                    b.Navigation("FormItem");

                    b.Navigation("FormVersion");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormDefinition<System.Guid>", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormSubmission<System.Guid>", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("SurvStation.Domain.Models.Forms.FormVersion<System.Guid>", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
